export const SCRAPED_REPOSITORY = Symbol('ScrapedRepository');

export const FIND_BY_ID_USECASE = Symbol('FIND_BY_ID_USECASE');
export const FIND_BY_SOURCE_ULR_USECASE= Symbol(' FIND_BY_SOURCE_ULR_USECASE');
export const SAVE_SCRAPED_CONTENT_USECASE = Symbol('SAVE_SCRAPED_CONTENT_USECASE');

